source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Sensorberg_Example', :exclusive => true do
  pod "Sensorberg", :path => "../"
end

target 'Sensorberg_Tests', :exclusive => true do
  pod "Sensorberg", :path => "../"

  
end
